### ISSUE TITLE
自用，求exe版本

### ISSUE THREAD

**Issue by WangFinn** [cycz/jdBuyMask#77]
之前用V2版本一直抢不到，群也满了，求exe文件。邮箱：370063235@qq.com

**Comment by cycz** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WangFinn"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月16日(星期天) 下午3:34
收件人:&nbsp;"cycz/jdBuyMask"<jdBuyMask@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[cycz/jdBuyMask] 自用，求exe版本 (#77)




之前用V2版本一直抢不到，群也满了，求exe文件。邮箱：370063235@qq.com
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

口罩小助手.zip (208.41M, 2020年02月23日 15:36 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=753162629c50c1979e3d975311340a4a52010352555659561b0201550e190c5602574f5b51575b48050855560e50010004095256373a38daece4b4b296e2c2afe01f180b473479&code=61bb748e
